pep8 installed: blessings==1.6,charm-tools==2.1.4,Cheetah==2.4.4,colander==1.3.1,configparser==3.5.0,ecdsa==0.13,enum34==1.1.6,flake8==3.0.4,functools32==3.2.3.post2,httplib2==0.9.2,iso8601==0.1.11,jsonschema==2.5.1,jujubundlelib==0.5.2,keyring==9.3.1,launchpadlib==1.10.4,lazr.authentication==0.1.3,lazr.restfulclient==0.13.1,lazr.uri==1.0.3,libcharmstore==0.0.3,Markdown==2.6.7,mccabe==0.5.2,oauth==1.0.1,otherstuf==1.1.0,paramiko==1.17.2,parse==1.6.6,path.py==8.2.1,pathspec==0.5.0,pbr==1.10.0,pkg-resources==0.0.0,pycodestyle==2.0.0,pycrypto==2.6.1,pyflakes==1.2.3,PyYAML==3.12,requests==2.11.1,ruamel.ordereddict==0.4.9,ruamel.yaml==0.12.14,SecretStorage==2.2.1,simplejson==3.8.2,six==1.10.0,stuf==0.9.16,testresources==2.0.1,theblues==0.3.6,translationstring==1.3,typing==3.5.2.2,virtualenv==15.0.3,wadllib==1.3.2,wsgi-intercept==1.4.1,zope.interface==4.3.2
pep8 runtests: PYTHONHASHSEED='0'
pep8 runtests: commands[0] | flake8 src/reactive src/lib unit_tests
py34 create: /home/charm/charms/layers/charm-trove/.tox/py34
ERROR: InterpreterNotFound: python3.4
py35 installed: Babel==2.3.4,charmhelpers==0.9.1,charms.openstack==0.0.1.dev1,charms.reactive==0.4.4,coverage==4.2,extras==1.0.0,fixtures==3.0.0,flake8==2.4.1,Jinja2==2.8,linecache2==1.0.0,MarkupSafe==0.23,mccabe==0.3.1,mock==2.0.0,netaddr==0.7.18,os-testr==0.8.0,pbr==1.10.0,pep8==1.7.0,pkg-resources==0.0.0,pyaml==16.9.0,pyflakes==0.8.1,python-mimeparse==1.5.5,python-subunit==1.2.0,pytz==2016.7,PyYAML==3.12,six==1.10.0,Tempita==0.5.2,testrepository==0.0.20,testtools==2.2.0,traceback2==1.4.0,unittest2==1.1.0
py35 runtests: PYTHONHASHSEED='0'
py35 runtests: commands[0] | ostestr
running=ONon-zero exit code (2) from test listing.
S_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ ./unit_tests --list 
--- import errors ---
Failed to import test module: unit_tests.test_trove_handlers
Traceback (most recent call last):
  File "/home/charm/charms/layers/charm-trove/.tox/py35/lib/python3.5/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/charm/charms/layers/charm-trove/.tox/py35/lib/python3.5/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/home/charm/charms/layers/charm-trove/unit_tests/test_trove_handlers.py", line 8, in <module>
    import reactive.designate_handlers as handlers
ImportError: No module named 'reactive.designate_handlers'

Failed to import test module: unit_tests.test_trove_utils
Traceback (most recent call last):
  File "/home/charm/charms/layers/charm-trove/.tox/py35/lib/python3.5/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/charm/charms/layers/charm-trove/.tox/py35/lib/python3.5/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/home/charm/charms/layers/charm-trove/unit_tests/test_trove_utils.py", line 4, in <module>
    import reactive.designate_utils as dutils
ImportError: No module named 'reactive.designate_utils'
The test run didn't actually run any tests

Slowest Tests:

ERROR: InvocationError: '/home/charm/charms/layers/charm-trove/.tox/py35/bin/ostestr'
___________________________________ summary ____________________________________
  pep8: commands succeeded
SKIPPED:  py34: InterpreterNotFound: python3.4
ERROR:   py35: commands failed
